Además de `E_ALL` tenemos otras opciones muy interesantes como pueden ser `E_NOTICE`, la cual nos ayuda dándonos también consejos de buena sintaxis.

Por cierto, si estas utilizando **PHP 7.x** los mensajes de error que has tenido han sido diferentes, pero con el mismo significado. Eso es porque ahora ya no se notifican por el mecanismo tradicional, si no que lanzan excepciones `Error`

**Jerarquia de Error:**

* Throwable
  * ​Error
    * Arithmetic Error
  * DivisionByZeroError
* ParseError 
  * Exception

Todas las excepciones de **PHP** y las de usuario de **PHP7** siguen esta base:

```php
class Exception
{
    protected $message = 'Unknown exception';   // mensaje de excepción
    private   $string;                          // caché de __toString
    protected $code = 0;                        // código de excepción definido por el usuario
    protected $file;                            // nombre de archivo fuente de la excepción
    protected $line;                            // línea fuente de la excepción
    private   $trace;                           // determinación del origen
    private   $previous;                        // excepción previa si la excepción está anidada

    public function __construct($message = null, $code = 0, Exception $previous = null);

    final private function __clone();           // Inhibe la clonación de excepciones.

    final public  function getMessage();        // mensaje de excepción
    final public  function getCode();           // código de excepción
    final public  function getFile();           // nombre de archivo fuente
    final public  function getLine();           // línea fuente
    final public  function getTrace();          // un array de backtrace()
    final public  function getPrevious();       // excepción anterior
    final public  function getTraceAsString();  // string formateado del seguimiento del origen

    // Sobrescribible
    public function __toString();               // string formateado para mostrar
}
```

> 💪 _Al igual que en otros lenguajes de programación en PHP podemos lanzar excepciones (`thrown`) y capturarlas (`catch`)._

> _Para poder cazarlas el código debe ejecutarse dentro de un bloque `try`. En caso de capturar una excepción se ejecutara el `catch` correspondiente, y de estar definido el `finally` tenga o no excepción._

## 🤔 ¿Qué es una excepción?

Una excepción es un objeto que describe un error o un comportamiento inesperado de un script PHP.

Las excepciones son lanzadas por muchas funciones y clases de PHP.

Las funciones y clases definidas por el usuario también pueden lanzar excepciones.

Las excepciones son una buena manera de detener una función cuando se encuentra con datos que no puede utilizar.

Lanzando una Excepción (`exception`)

La sentencia `throw` permite a una función o método definido por el usuario lanzar una excepción. Cuando se lanza una excepción, el código que la sigue no se ejecuta.

Si una excepción no es capturada, se producirá un error fatal con el mensaje "`Uncaught Exception`".

Intentemos lanzar una excepción sin atraparla:

```php
function divide($dividendo, $divisor) {
  if($divisor == 0) {
    throw new Exception("Division by zero");
  }
  return $dividendo / $divisor;
}

echo divide(5, 0);
```

El resultado será algo parecido a esto:

```php
Fatal error: Uncaught Exception: Division by zero in C:\webfolder\test.php:4
Stack trace: #0 C:\webfolder\test.php(9):
divide(5, 0) #1 {main} thrown in C:\webfolder\test.php on line 4
```

## 📥 La sentencia `try ... catch`

Para evitar el error del ejemplo anterior, podemos utilizar la sentencia `try...catch` para atrapar excepciones y continuar el proceso.

📏 **Sintaxis:**
```php
try {
  code that can throw exceptions
} catch(Exception $e) {
  code that runs when an exception is caught
}
```

**Ejemplo**

Mostrar un mensaje cuando se lanza una excepción:

```php
function divide($dividend, $divisor) {
  if($divisor == 0) {
    throw new Exception("Division by zero");
  }
  return $dividend / $divisor;
}

try {
  echo divide(5, 0);
} catch(Exception $e) {
  echo "Unable to divide.";
}
```

El bloque `catch` indica qué tipo de excepción debe ser capturada y el nombre de la variable que puede ser utilizada para acceder a la excepción. En el ejemplo anterior, el tipo de excepción es `Exception` y el nombre de la variable es `$e`.

## 👍 La sentencia `try...catch...finally`

La sentencia `try...catch...finally` puede utilizarse para capturar excepciones. El código en el bloque `finally` siempre se ejecutará independientemente de si se ha capturado una excepción. Si el bloque `finally` está presente, el bloque catch es opcional.

📏 **Sintaxis:**
```php
try {
  code that can throw exceptions
} catch(Exception $e) {
  code that runs when an exception is caught
} finally {
  code that always runs regardless of whether an exception was caught
}
```

**Ejemplo**

Mostrar un mensaje cuando se lanza una excepción y luego indicar que el proceso ha terminado:

```php
function divide($dividend, $divisor) {
  if($divisor == 0) {
    throw new Exception("Division by zero");
  }
  return $dividend / $divisor;
}

try {
  echo divide(5, 0);
} catch(Exception $e) {
  echo "Unable to divide. ";
} finally {
  echo "Process complete.";
}
```

**Ejemplo**

Imprimir una cadena aunque no se haya capturado una excepción:

```php
function divide($dividend, $divisor) {
  if($divisor == 0) {
    throw new Exception("Division by zero");
  }
  return $dividend / $divisor;
}

try {
  echo divide(5, 0);
} finally {
  echo "Process complete.";
}
```

## El objeto de excepción

El objeto de excepción contiene información sobre el error o el comportamiento inesperado que ha encontrado la función.

📏 **Sintaxis:**
```php
new Exception(mensaje, código, anterior)
```

### Valores de los parámetros
| Parámetro | Descripción |
|-----------|-------------|
| `message` | _Opcional._ Una cadena que describe por qué se lanzó la excepción |
| `code`    | _Opcional._ Un número entero que puede utilizarse para distinguir fácilmente esta excepción de otras del mismo tipo |
| `previous` | _Opcional._ Si esta excepción fue lanzada en un bloque `catch` de otra excepción, se recomienda pasar esa excepción en este parámetro |

### Métodos

Cuando se atrapa una excepción, la siguiente tabla muestra algunos de los métodos que se pueden utilizar para obtener información sobre la excepción:

| Método | Descripción |
|--------|-------------|
| `getMessage()`| Devuelve una cadena que describe el motivo de la excepción lanzada |
| `getPrevious()`|  Si esta excepción fue lanzada por otra, este método devuelve la excepción anterior. Si no, devuelve `null` |
| `getCode()`|  Devuelve el código de la excepción |
| `getFile()`|  Devuelve la ruta completa del archivo en el que se lanzó la excepción |
| `getLine()`|  Devuelve el número de línea de la línea de código que lanzó la excepción |

**Ejemplo**

Devuelve información sobre una excepción lanzada:

```php
function divide($dividend, $divisor) {
  if($divisor == 0) {
    throw new Exception("Division by zero", 1);
  }
  return $dividend / $divisor;
}

try {
  echo divide(5, 0);
} catch(Exception $ex) {
  $code = $ex->getCode();
  $message = $ex->getMessage();
  $file = $ex->getFile();
  $line = $ex->getLine();
  echo "Exception thrown in $file on line $line: [Code $code]
  $message";
}
```
